<SECTION>
                    <DIV class="header-modules">
                        <DIV class="container">
                            <DIV class="row">
                                <DIV class="span12">
                                    <SCRIPT>
                                        jQuery(function() {
                                            jQuery('#camera_wrap_0').camera({
                                                fx: 'stampede',
                                                navigation: false,
                                                playPause: false,
                                                thumbnails: false,
                                                barPosition: 'top',
                                                loader: false,
                                                time: 3000,
                                                transPeriod: 800,
                                                alignment: 'center',
                                                autoAdvance: true,
                                                mobileAutoAdvance: true,
                                                barDirection: 'leftToRight',
                                                barPosition: 'bottom',
                                                easing: 'easeInOutExpo',
                                                fx: 'simpleFade',
                                                height: '28.29%',
                                                minHeight: '90px',
                                                hover: true,
                                                pagination: true,
                                                loaderColor: '#1f1f1f',
                                                loaderBgColor: 'transparent',
                                                loaderOpacity: 1,
                                                loaderPadding: 0,
                                                loaderStroke: 3
                                            });
                                        });
                                    </SCRIPT>

                                    <DIV class="fluid_container">
                                        <DIV id="camera_wrap_0">
                                            <DIV title="" data-src="https://livedemo00.template-help.com/opencart_45557/image/cache/data/slide-3-1170x331.jpg" data-thumb="https://livedemo00.template-help.com/opencart_45557/image/cache/data/slide-3-1170x331.jpg">
                                                <DIV class="camera_caption fadeIn">
                                                    <H1>My Website</H1>
                                                    <P>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </P>
                                                    <A href="_product/product&amp;product_id=29">Shop 
now!<I class="icon-chevron-sign-right"></I></A> </DIV>
                                            </DIV>
                                            <DIV title="" data-src="https://livedemo00.template-help.com/opencart_45557/image/cache/data/slide-2-1170x331.jpg" data-thumb="https://livedemo00.template-help.com/opencart_45557/image/cache/data/slide-2-1170x331.jpg">
                                                <DIV class="camera_caption fadeIn">
                                                    <H1>E-Commerce</H1>
                                                    <P>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </P>
                                                    <A href="_product/product&amp;product_id=32">Shop 
now!<I class="icon-chevron-sign-right"></I></A> </DIV>
                                            </DIV>
                                            <DIV title="" data-src="https://livedemo00.template-help.com/opencart_45557/image/cache/data/slide-1-1170x331.jpg" data-thumb="https://livedemo00.template-help.com/opencart_45557/image/cache/data/slide-1-1170x331.jpg">
                                                <DIV class="camera_caption fadeIn">
                                                    <H1>Use Business Email</H1>
                                                    <P>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </P>
                                                    <A href="_product/product&amp;product_id=28">Shop 
now!<I class="icon-chevron-sign-right"></I></A> </DIV>
                                            </DIV>
                                        </DIV>
                                        <DIV class="clear"></DIV>
                                    </DIV>
                                    <DIV class="banner row" id="banner0">
                                        <DIV class="span4">
                                            <IMG title="" alt="" src="<?php echo URL_UI_HOME_THEMES;?>template_files/banner-1-368x231.jpg">
                                            <DIV class="s-desc">
                                                <H1>01</H1>
                                                <H2>Bronze
                                                    <SPAN>$25.89 <B>/month</B></SPAN>
                                                </H2>
                                                <P>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt.</P>
                                                <A href="_product/product&amp;product_id=28">Shop 
now!</A>
                                            </DIV>
                                        </DIV>
                                        <DIV class="span4">
                                            <IMG title="" alt="" src="<?php echo URL_UI_HOME_THEMES;?>template_files/banner-1-368x231.jpg">
                                            <DIV class="s-desc">
                                                <H1>02</H1>
                                                <H2>Silver
                                                    <SPAN>$35.89 <B>/month</B></SPAN>
                                                </H2>
                                                <P>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt.</P>
                                                <A href="_product/product&amp;product_id=29">Shop 
now!</A>
                                            </DIV>
                                        </DIV>
                                        <DIV class="span4">
                                            <IMG title="" alt="" src="<?php echo URL_UI_HOME_THEMES;?>template_files/banner-1-368x231.jpg">
                                            <DIV class="s-desc">
                                                <H1>03</H1>
                                                <H2>Gold
                                                    <SPAN>$45.89 <B>/month</B></SPAN>
                                                </H2>
                                                <P>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt.</P>
                                                <A href="_product/product&amp;product_id=32">Shop 
now!</A>
                                            </DIV>
                                        </DIV>
                                    </DIV>
                                </DIV>
                                <DIV class="clear"></DIV>
                            </DIV>
                        </DIV>
                    </DIV>
                    <DIV class="clear"></DIV>
                    <DIV id="container">
                        <P id="back-top">
                            <A href="https://livedemo00.template-help.com/opencart_45557/#top"><SPAN></SPAN></A>
                        </P>
                        <DIV class="container">
                            <DIV id="notification"></DIV>
                            <DIV class="row">
                                <DIV class="span12">
                                    <DIV class="row">
                                        <DIV class="  span12 " id="content">
                                            <SCRIPT type="text/javascript">
                                                if ($('.container').width() > 723) {
                                                    (function($) {
                                                        $.fn.equalHeights = function(minHeight, maxHeight) {
                                                            tallest = (minHeight) ? minHeight : 0;
                                                            this.each(function() {
                                                                if ($(this).height() > tallest) {
                                                                    tallest = $(this).height()
                                                                }
                                                            });
                                                            if ((maxHeight) && tallest > maxHeight) tallest = maxHeight;
                                                            return this.each(function() {
                                                                $(this).height(tallest)
                                                            })
                                                        }
                                                    })(jQuery)
                                                    $(window).load(function() {
                                                        if ($(".maxheight-feat").length) {
                                                            $(".maxheight-feat").equalHeights()
                                                        }
                                                    });
                                                };
                                            </SCRIPT>

                                            <DIV class="box featured">
                                                <DIV class="box-heading">Featured Products</DIV>
                                                <DIV class="box-content">
                                                    <DIV class="box-product">
                                                        <UL class="row">
                                                            <LI class="first-in-line last_line span3">
                                                                <SCRIPT type="text/javascript">
                                                                    $(document).ready(function() {
                                                                        $("a.colorbox1").colorbox({
                                                                            rel: 'colorbox',
                                                                            inline: true,
                                                                            html: true,
                                                                            width: '58%',
                                                                            maxWidth: '780px',
                                                                            height: '70%',
                                                                            opacity: 0.6,
                                                                            open: false,
                                                                            returnFocus: false,
                                                                            fixed: false,
                                                                            title: false,
                                                                            href: '.quick-view1',
                                                                            current: 'Product {current} of {total}'
                                                                        });
                                                                    });
                                                                </SCRIPT>

                                                                <DIV class="image2">
                                                                    <A href="_product/product&amp;product_id=44">
                                                                        <IMG id="img_44" alt="Ispsum dolor sit amet tation ullamcorper" src="<?php echo URL_UI_HOME_THEMES;?>template_files/FileMaker%2520Server%252011.0%2520Education%2520(Mac-Windows)%25201%2520copy-180x180.png">
                                                                    </A>
                                                                </DIV>
                                                                <DIV style="display: none;">
                                                                    <DIV class="quick-view1 preview">
                                                                        <DIV class="wrapper marg row-fluid">
                                                                            <DIV class="left span4">
                                                                                <DIV class="image3">
                                                                                    <A href="_product/product&amp;product_id=44">
                                                                                        <IMG alt="Ispsum dolor sit amet tation ullamcorper" src="<?php echo URL_UI_HOME_THEMES;?>template_files/FileMaker%2520Server%252011.0%2520Education%2520(Mac-Windows)%25201%2520copy-270x270.png">
                                                                                    </A>
                                                                                </DIV>
                                                                            </DIV>
                                                                            <DIV class="right span8">
                                                                                <H2>Ispsum dolor sit amet tation ullamcorper</H2>
                                                                                <DIV class="inf">
                                                                                    <SPAN class="manufacture">Brand: <A href="_product/manufacturer/info&amp;manufacturer_id=5">Et 
  dolore magna</A></SPAN>
                                                                                    <SPAN class="model">Model:Product 17</SPAN>
                                                                                    <SPAN class="prod-stock-2">Availability:</SPAN>
                                                                                    <SPAN class="prod-stock">In Stock</SPAN>
                                                                                    <DIV class="price">
                                                                                        <SPAN class="text-price">Price: </SPAN>$1,177.00
                                                                                    </DIV>
                                                                                </DIV>
                                                                                <DIV class="cart-button">
                                                                                    <DIV class="cart">
                                                                                        <A title="Add to cart" class="button addToCart-1 " data-id="44;"><SPAN>Add 
  to cart</SPAN> </A> </DIV>
                                                                                    <DIV class="wishlist">
                                                                                        <A title="Add to Wish List" class="tooltip-1" onclick="addToWishList('44');"><I 
  class="icon-star"></I> <SPAN>Add to Wish List</SPAN> </A>
                                                                                    </DIV>
                                                                                    <DIV class="compare">
                                                                                        <A title="Add to Compare" class="tooltip-1" onclick="addToCompare('44');"><I 
  class="icon-bar-chart"></I> <SPAN>Add to Compare</SPAN> </A>
                                                                                    </DIV>
                                                                                    <SPAN class="clear"></SPAN>
                                                                                </DIV>
                                                                                <DIV class="clear"></DIV>
                                                                                <DIV class="rating">
                                                                                    <IMG height="18" alt="0" src="<?php echo URL_UI_HOME_THEMES;?>template_files/stars-0.png">
                                                                                </DIV>
                                                                            </DIV>
                                                                        </DIV>
                                                                        <DIV class="description">
                                                                            <P>We are living in the epoch of
                                                                                <STRONG>great technical progress</STRONG> and we are sure that
                                                                                <EM>new technologies</EM> are our future. You know that computers are being applied in all spheres of society. It is a tremendous achievement of mankind. It is
                                                                                <STRONG>totally safe</STRONG> for environment and for the people, it runs with electricity.</P>
                                                                            <P>The most
                                                                                <EM>important</EM> thing is that the computer technology has great perspectives for
                                                                                <STRONG>further development</STRONG> and it could be called a panacea for humanity. It seems that computer is such a revolutionary invention that we could not even realize the true extent of its significance. Some people are even
                                                                                <EM>afraid</EM> of such rapid and striking computer expansion; they state that mankind is in danger because of it. Their main argument is the problem of artificial intelligence. But we hope that all these
                                                                                <STRONG>problems will disappear</STRONG> soon.</P>
                                                                            <P>So, it is natural that this sphere is one of the
                                                                                <STRONG>most 
  popular</STRONG> ones and it is
                                                                                <EM>really hard</EM> to offer computer hardware because of
                                                                                <STRONG>great number</STRONG> of competitors. We are providing a great choice of
                                                                                <EM>different</EM> commodities. We are producing
                                                                                <STRONG>reliable and durable</STRONG> goods</P>
                                                                        </DIV>
                                                                    </DIV>
                                                                </DIV>
                                                                <A class="colorbox1 quick-view-button" href="_product/product&amp;product_id=44" rel="colorbox"><I class=" icon-search "></I></A>
                                                                <DIV class="inner">
                                                                    <DIV class="f-left">
                                                                        <DIV class="name maxheight-feat">
                                                                            <A href="_product/product&amp;product_id=44">Ispsum 
  dolor sit amet tat...</A>
                                                                        </DIV>
                                                                        <DIV class="description">We are living in the epoch of great technical progress and we are sure...</DIV>
                                                                        <DIV class="price">$1,177.00 </DIV>
                                                                    </DIV>
                                                                    <DIV class="cart-button">
                                                                        <DIV class="cart">
                                                                            <A title="Add to cart" class="button addToCart" data-id="44;"><SPAN>Add 
  to cart</SPAN></A>
                                                                        </DIV>
                                                                        <SPAN class="clear"></SPAN>
                                                                    </DIV>
                                                                    <DIV class="clear"></DIV>
                                                                </DIV>
                                                                <DIV class="clear"></DIV>
                                                            </LI>
                                                            <LI class=" last_line span3">
                                                                <SCRIPT type="text/javascript">
                                                                    $(document).ready(function() {
                                                                        $("a.colorbox2").colorbox({
                                                                            rel: 'colorbox',
                                                                            inline: true,
                                                                            html: true,
                                                                            width: '58%',
                                                                            maxWidth: '780px',
                                                                            height: '70%',
                                                                            opacity: 0.6,
                                                                            open: false,
                                                                            returnFocus: false,
                                                                            fixed: false,
                                                                            title: false,
                                                                            href: '.quick-view2',
                                                                            current: 'Product {current} of {total}'
                                                                        });
                                                                    });
                                                                </SCRIPT>

                                                                <DIV class="image2">
                                                                    <A href="_product/product&amp;product_id=36">
                                                                        <IMG id="img_36" alt="Ecco enswom sucaal tation ullamcorper" src="<?php echo URL_UI_HOME_THEMES;?>template_files/Apple%2520External%2520SuperDrive%2520for%2520MacBook%2520Air%2520&amp;%2520Mac%2520mini%2520Server%25201%2520copy-180x180.png">
                                                                    </A>
                                                                </DIV>
                                                                <DIV style="display: none;">
                                                                    <DIV class="quick-view2 preview">
                                                                        <DIV class="wrapper marg row-fluid">
                                                                            <DIV class="left span4">
                                                                                <DIV class="image3">
                                                                                    <A href="_product/product&amp;product_id=36">
                                                                                        <IMG alt="Ecco enswom sucaal tation ullamcorper" src="<?php echo URL_UI_HOME_THEMES;?>template_files/Apple%2520External%2520SuperDrive%2520for%2520MacBook%2520Air%2520&amp;%2520Mac%2520mini%2520Server%25201%2520copy-270x270.png">
                                                                                    </A>
                                                                                </DIV>
                                                                            </DIV>
                                                                            <DIV class="right span8">
                                                                                <H2>Ecco enswom sucaal tation ullamcorper</H2>
                                                                                <DIV class="inf">
                                                                                    <SPAN class="manufacture">Brand: <A href="_product/manufacturer/info&amp;manufacturer_id=5">Et 
  dolore magna</A></SPAN>
                                                                                    <SPAN class="model">Model:Product 9</SPAN>
                                                                                    <SPAN class="prod-stock-2">Availability:</SPAN>
                                                                                    <SPAN class="prod-stock">In Stock</SPAN>
                                                                                    <DIV class="price">
                                                                                        <SPAN class="text-price">Price: </SPAN>$119.50 </DIV>
                                                                                </DIV>
                                                                                <DIV class="cart-button">
                                                                                    <DIV class="cart">
                                                                                        <A title="Add to cart" class="button addToCart-1 " data-id="36;"><SPAN>Add 
  to cart</SPAN> </A> </DIV>
                                                                                    <DIV class="wishlist">
                                                                                        <A title="Add to Wish List" class="tooltip-1" onclick="addToWishList('36');"><I 
  class="icon-star"></I> <SPAN>Add to Wish List</SPAN> </A>
                                                                                    </DIV>
                                                                                    <DIV class="compare">
                                                                                        <A title="Add to Compare" class="tooltip-1" onclick="addToCompare('36');"><I 
  class="icon-bar-chart"></I> <SPAN>Add to Compare</SPAN> </A>
                                                                                    </DIV>
                                                                                    <SPAN class="clear"></SPAN>
                                                                                </DIV>
                                                                                <DIV class="clear"></DIV>
                                                                                <DIV class="rating">
                                                                                    <IMG height="18" alt="0" src="<?php echo URL_UI_HOME_THEMES;?>template_files/stars-0.png">
                                                                                </DIV>
                                                                            </DIV>
                                                                        </DIV>
                                                                        <DIV class="description">
                                                                            <P>We are living in the epoch of
                                                                                <STRONG>great technical progress</STRONG> and we are sure that
                                                                                <EM>new technologies</EM> are our future. You know that computers are being applied in all spheres of society. It is a tremendous achievement of mankind. It is
                                                                                <STRONG>totally safe</STRONG> for environment and for the people, it runs with electricity.</P>
                                                                            <P>The most
                                                                                <EM>important</EM> thing is that the computer technology has great perspectives for
                                                                                <STRONG>further development</STRONG> and it could be called a panacea for humanity. It seems that computer is such a revolutionary invention that we could not even realize the true extent of its significance. Some people are even
                                                                                <EM>afraid</EM> of such rapid and striking computer expansion; they state that mankind is in danger because of it. Their main argument is the problem of artificial intelligence. But we hope that all these
                                                                                <STRONG>problems will disappear</STRONG> soon.</P>
                                                                            <P>So, it is natural that this sphere is one of the
                                                                                <STRONG>most 
  popular</STRONG> ones and it is
                                                                                <EM>really hard</EM> to offer computer hardware because of
                                                                                <STRONG>great number</STRONG> of competitors. We are providing a great choice of
                                                                                <EM>different</EM> commodities. We are producing
                                                                                <STRONG>reliable and durable</STRONG> goods</P>
                                                                        </DIV>
                                                                    </DIV>
                                                                </DIV>
                                                                <A class="colorbox2 quick-view-button" href="_product/product&amp;product_id=36" rel="colorbox"><I class=" icon-search "></I></A>
                                                                <DIV class="inner">
                                                                    <DIV class="f-left">
                                                                        <DIV class="name maxheight-feat">
                                                                            <A href="_product/product&amp;product_id=36">Ecco 
  enswom sucaal tation...</A>
                                                                        </DIV>
                                                                        <DIV class="description">We are living in the epoch of great technical progress and we are sure...</DIV>
                                                                        <DIV class="price">$119.50 </DIV>
                                                                    </DIV>
                                                                    <DIV class="cart-button">
                                                                        <DIV class="cart">
                                                                            <A title="Add to cart" class="button addToCart" data-id="36;"><SPAN>Add 
  to cart</SPAN></A>
                                                                        </DIV>
                                                                        <SPAN class="clear"></SPAN>
                                                                    </DIV>
                                                                    <DIV class="clear"></DIV>
                                                                </DIV>
                                                                <DIV class="clear"></DIV>
                                                            </LI>
                                                            <LI class=" last_line span3">
                                                                <SCRIPT type="text/javascript">
                                                                    $(document).ready(function() {
                                                                        $("a.colorbox3").colorbox({
                                                                            rel: 'colorbox',
                                                                            inline: true,
                                                                            html: true,
                                                                            width: '58%',
                                                                            maxWidth: '780px',
                                                                            height: '70%',
                                                                            opacity: 0.6,
                                                                            open: false,
                                                                            returnFocus: false,
                                                                            fixed: false,
                                                                            title: false,
                                                                            href: '.quick-view3',
                                                                            current: 'Product {current} of {total}'
                                                                        });
                                                                    });
                                                                </SCRIPT>

                                                                <DIV class="image2">
                                                                    <A href="_product/product&amp;product_id=41">
                                                                        <IMG id="img_41" alt="Gyllamn sticba Gyllamn sticba tation ullamcorper" src="<?php echo URL_UI_HOME_THEMES;?>template_files/Apple%2520Mac%2520Pro%2520Server%2520Quad-Core%2520Desktop%2520Computer%2520Workstation%25201%2520copy-180x180.png">
                                                                    </A>
                                                                </DIV>
                                                                <DIV style="display: none;">
                                                                    <DIV class="quick-view3 preview">
                                                                        <DIV class="wrapper marg row-fluid">
                                                                            <DIV class="left span4">
                                                                                <DIV class="image3">
                                                                                    <A href="_product/product&amp;product_id=41">
                                                                                        <IMG alt="Gyllamn sticba Gyllamn sticba tation ullamcorper" src="<?php echo URL_UI_HOME_THEMES;?>template_files/Apple%2520Mac%2520Pro%2520Server%2520Quad-Core%2520Desktop%2520Computer%2520Workstation%25201%2520copy-270x270.png">
                                                                                    </A>
                                                                                </DIV>
                                                                            </DIV>
                                                                            <DIV class="right span8">
                                                                                <H2>Gyllamn sticba Gyllamn sticba tation ullamcorper</H2>
                                                                                <DIV class="inf">
                                                                                    <SPAN class="model">Model:Product 14</SPAN>
                                                                                    <SPAN class="prod-stock-2">Availability:</SPAN>
                                                                                    <SPAN class="prod-stock">In Stock</SPAN>
                                                                                    <DIV class="price">
                                                                                        <SPAN class="text-price">Price: </SPAN>
                                                                                        <SPAN class="price-new">$118.33</SPAN>
                                                                                        <SPAN class="price-old">$119.50</SPAN>
                                                                                    </DIV>
                                                                                </DIV>
                                                                                <DIV class="cart-button">
                                                                                    <DIV class="cart">
                                                                                        <A title="Add to cart" class="button addToCart-1 " data-id="41;"><SPAN>Add 
  to cart</SPAN> </A> </DIV>
                                                                                    <DIV class="wishlist">
                                                                                        <A title="Add to Wish List" class="tooltip-1" onclick="addToWishList('41');"><I 
  class="icon-star"></I> <SPAN>Add to Wish List</SPAN> </A>
                                                                                    </DIV>
                                                                                    <DIV class="compare">
                                                                                        <A title="Add to Compare" class="tooltip-1" onclick="addToCompare('41');"><I 
  class="icon-bar-chart"></I> <SPAN>Add to Compare</SPAN> </A>
                                                                                    </DIV>
                                                                                    <SPAN class="clear"></SPAN>
                                                                                </DIV>
                                                                                <DIV class="clear"></DIV>
                                                                                <DIV class="rating">
                                                                                    <IMG height="18" alt="0" src="<?php echo URL_UI_HOME_THEMES;?>template_files/stars-0.png">
                                                                                </DIV>
                                                                            </DIV>
                                                                        </DIV>
                                                                        <DIV class="description">
                                                                            <P>We are living in the epoch of
                                                                                <STRONG>great technical progress</STRONG> and we are sure that
                                                                                <EM>new technologies</EM> are our future. You know that computers are being applied in all spheres of society. It is a tremendous achievement of mankind. It is
                                                                                <STRONG>totally safe</STRONG> for environment and for the people, it runs with electricity.</P>
                                                                            <P>The most
                                                                                <EM>important</EM> thing is that the computer technology has great perspectives for
                                                                                <STRONG>further development</STRONG> and it could be called a panacea for humanity. It seems that computer is such a revolutionary invention that we could not even realize the true extent of its significance. Some people are even
                                                                                <EM>afraid</EM> of such rapid and striking computer expansion; they state that mankind is in danger because of it. Their main argument is the problem of artificial intelligence. But we hope that all these
                                                                                <STRONG>problems will disappear</STRONG> soon.</P>
                                                                            <P>So, it is natural that this sphere is one of the
                                                                                <STRONG>most 
  popular</STRONG> ones and it is
                                                                                <EM>really hard</EM> to offer computer hardware because of
                                                                                <STRONG>great number</STRONG> of competitors. We are providing a great choice of
                                                                                <EM>different</EM> commodities. We are producing
                                                                                <STRONG>reliable and durable</STRONG> goods</P>
                                                                        </DIV>
                                                                    </DIV>
                                                                </DIV>
                                                                <A class="colorbox3 quick-view-button" href="_product/product&amp;product_id=41" rel="colorbox"><I class=" icon-search "></I></A>
                                                                <DIV class="inner">
                                                                    <DIV class="f-left">
                                                                        <DIV class="name maxheight-feat">
                                                                            <A href="_product/product&amp;product_id=41">Gyllamn 
  sticba Gyllamn st...</A>
                                                                        </DIV>
                                                                        <DIV class="description">We are living in the epoch of great technical progress and we are sure...</DIV>
                                                                        <DIV class="price">
                                                                            <SPAN class="price-new">$118.33</SPAN>
                                                                            <SPAN class="price-old">$119.50</SPAN>
                                                                        </DIV>
                                                                    </DIV>
                                                                    <DIV class="cart-button">
                                                                        <DIV class="cart">
                                                                            <A title="Add to cart" class="button addToCart" data-id="41;"><SPAN>Add 
  to cart</SPAN></A>
                                                                        </DIV>
                                                                        <SPAN class="clear"></SPAN>
                                                                    </DIV>
                                                                    <DIV class="clear"></DIV>
                                                                </DIV>
                                                                <DIV class="clear"></DIV>
                                                            </LI>
                                                            <LI class="last-in-line last_line span3">
                                                                <SCRIPT type="text/javascript">
                                                                    $(document).ready(function() {
                                                                        $("a.colorbox4").colorbox({
                                                                            rel: 'colorbox',
                                                                            inline: true,
                                                                            html: true,
                                                                            width: '58%',
                                                                            maxWidth: '780px',
                                                                            height: '70%',
                                                                            opacity: 0.6,
                                                                            open: false,
                                                                            returnFocus: false,
                                                                            fixed: false,
                                                                            title: false,
                                                                            href: '.quick-view4',
                                                                            current: 'Product {current} of {total}'
                                                                        });
                                                                    });
                                                                </SCRIPT>

                                                                <DIV class="image2">
                                                                    <A href="_product/product&amp;product_id=42">
                                                                        <IMG id="img_42" alt="Lorem ipsum dolor sit tation ullamcorper" src="<?php echo URL_UI_HOME_THEMES;?>template_files/Gefen%2520EXT-USB-400FON%2520USB%25202.0%2520Extender%25201%2520copy-180x180.png">
                                                                    </A>
                                                                </DIV>
                                                                <DIV style="display: none;">
                                                                    <DIV class="quick-view4 preview">
                                                                        <DIV class="wrapper marg row-fluid">
                                                                            <DIV class="left span4">
                                                                                <DIV class="image3">
                                                                                    <A href="_product/product&amp;product_id=42">
                                                                                        <IMG alt="Lorem ipsum dolor sit tation ullamcorper" src="<?php echo URL_UI_HOME_THEMES;?>template_files/Gefen%2520EXT-USB-400FON%2520USB%25202.0%2520Extender%25201%2520copy-270x270.png">
                                                                                    </A>
                                                                                </DIV>
                                                                            </DIV>
                                                                            <DIV class="right span8">
                                                                                <H2>Lorem ipsum dolor sit tation ullamcorper</H2>
                                                                                <DIV class="inf">
                                                                                    <SPAN class="manufacture">Brand: <A href="https://livedemo00.template-help.com/opencart_45557/apple">Ut 
  enim ad minim</A></SPAN>
                                                                                    <SPAN class="model">Model:Product 15</SPAN>
                                                                                    <SPAN class="prod-stock-2">Availability:</SPAN>
                                                                                    <SPAN class="prod-stock">In 
  Stock</SPAN>
                                                                                    <DIV class="price">
                                                                                        <SPAN class="text-price">Price: </SPAN>
                                                                                        <SPAN class="price-new">$107.75</SPAN>
                                                                                        <SPAN class="price-old">$119.50</SPAN>
                                                                                    </DIV>
                                                                                </DIV>
                                                                                <DIV class="cart-button">
                                                                                    <DIV class="cart">
                                                                                        <A title="Add to cart" class="button addToCart-1 " data-id="42;"><SPAN>Add 
  to cart</SPAN> </A> </DIV>
                                                                                    <DIV class="wishlist">
                                                                                        <A title="Add to Wish List" class="tooltip-1" onclick="addToWishList('42');"><I 
  class="icon-star"></I> <SPAN>Add to Wish List</SPAN> </A>
                                                                                    </DIV>
                                                                                    <DIV class="compare">
                                                                                        <A title="Add to Compare" class="tooltip-1" onclick="addToCompare('42');"><I 
  class="icon-bar-chart"></I> <SPAN>Add to Compare</SPAN> </A>
                                                                                    </DIV>
                                                                                    <SPAN class="clear"></SPAN>
                                                                                </DIV>
                                                                                <DIV class="clear"></DIV>
                                                                                <DIV class="rating">
                                                                                    <IMG height="18" alt="0" src="<?php echo URL_UI_HOME_THEMES;?>template_files/stars-0.png">
                                                                                </DIV>
                                                                            </DIV>
                                                                        </DIV>
                                                                        <DIV class="description">
                                                                            <P>We are living in the epoch of
                                                                                <STRONG>great technical progress</STRONG> and we are sure that
                                                                                <EM>new technologies</EM> are our future. You know that computers are being applied in all spheres of society. It is a tremendous achievement of mankind. It is
                                                                                <STRONG>totally safe</STRONG> for environment and for the people, it runs with electricity.</P>
                                                                            <P>The most
                                                                                <EM>important</EM> thing is that the computer technology has great perspectives for
                                                                                <STRONG>further development</STRONG> and it could be called a panacea for humanity. It seems that computer is such a revolutionary invention that we could not even realize the true extent of its significance. Some people are even
                                                                                <EM>afraid</EM> of such rapid and striking computer expansion; they state that mankind is in danger because of it. Their main argument is the problem of artificial intelligence. But we hope that all these
                                                                                <STRONG>problems will disappear</STRONG> soon.</P>
                                                                            <P>So, it is natural that this sphere is one of the
                                                                                <STRONG>most 
  popular</STRONG> ones and it is
                                                                                <EM>really hard</EM> to offer computer hardware because of
                                                                                <STRONG>great number</STRONG> of competitors. We are providing a great choice of
                                                                                <EM>different</EM> commodities. We are producing
                                                                                <STRONG>reliable and durable</STRONG> goods</P>
                                                                        </DIV>
                                                                    </DIV>
                                                                </DIV>
                                                                <A class="colorbox4 quick-view-button" href="_product/product&amp;product_id=42" rel="colorbox"><I class=" icon-search "></I></A>
                                                                <DIV class="inner">
                                                                    <DIV class="f-left">
                                                                        <DIV class="name maxheight-feat">
                                                                            <A href="_product/product&amp;product_id=42">Lorem 
  ipsum dolor sit tat...</A>
                                                                        </DIV>
                                                                        <DIV class="description">We are living in the epoch of great technical progress and we are sure...</DIV>
                                                                        <DIV class="price">
                                                                            <SPAN class="price-new">$107.75</SPAN>
                                                                            <SPAN class="price-old">$119.50</SPAN>
                                                                        </DIV>
                                                                    </DIV>
                                                                    <DIV class="cart-button">
                                                                        <DIV class="cart">
                                                                            <A title="Add to cart" class="button addToCart" data-id="42;"><SPAN>Add 
  to cart</SPAN></A>
                                                                        </DIV>
                                                                        <SPAN class="clear"></SPAN>
                                                                    </DIV>
                                                                    <DIV class="clear"></DIV>
                                                                </DIV>
                                                                <DIV class="clear"></DIV>
                                                            </LI>
                                                        </UL>
                                                    </DIV>
                                                    <DIV class="clear"></DIV>
                                                </DIV>
                                            </DIV>
                                            <DIV class="clear"></DIV>
                                            <DIV class="wrapper">
                                                <DIV id="carousel0">
                                                    <UL class="jcarousel-skin-opencart"></UL>
                                                </DIV>
                                            </DIV>
                                            <SCRIPT type="text/javascript">
                                                <!--
                                                $('#carousel0 ul').jcarousel({
                                                    vertical: false,
                                                    visible: 5,
                                                    scroll: 3
                                                });
                                                //-->
                                            </SCRIPT>

                                            <H1 style="display: none;">Hosting</H1>
                                        </DIV>
                                    </DIV>
                                </DIV>
                                <DIV class="clear"></DIV>
                            </DIV>
                        </DIV>
                    </DIV>
                    <DIV class="clear"></DIV>
                </SECTION>